
# [from here](https://aroussi.com/post/download-options-data)

# [](https://github.com/ranaroussi/yfinance)

In [1]:
import yfinance as yf
aapl = yf.Ticker("TREX")
aapl.info
hist = aapl.history(period="max")
hist.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1999-04-08 00:00:00-04:00,1.250000,1.562500,1.250000,1.421875,7154400,0.0,0.0
1999-04-09 00:00:00-04:00,1.531250,1.734375,1.507813,1.609375,2672800,0.0,0.0
1999-04-12 00:00:00-04:00,1.625000,1.703125,1.570313,1.625000,1526400,0.0,0.0
1999-04-13 00:00:00-04:00,1.664063,1.765625,1.632813,1.718750,512000,0.0,0.0
1999-04-14 00:00:00-04:00,1.726563,1.742188,1.625000,1.710938,900000,0.0,0.0

In [14]:
aapl.actions

                           Dividends  Stock Splits
Date
2014-05-08 00:00:00-04:00        0.0           2.0
2018-06-19 00:00:00-04:00        0.0           2.0
2020-09-15 00:00:00-04:00        0.0           2.0

In [15]:
aapl.dividends

Series([], Name: Dividends, dtype: float64)

In [16]:
aapl.financials

,2023-12-31,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,0.0,-3886596.0,-11013517.565934,0.0,NaN
Tax Rate For Calcs,0.256,0.252,0.242034,0.251468,NaN
Normalized EBITDA,326393000.0,321879000.0,402330000.0,251574000.0,NaN
Total Unusual Items,0.0,-15423000.0,-45504000.0,0.0,NaN
Total Unusual Items Excluding Goodwill,0.0,-15423000.0,-45504000.0,0.0,NaN
Net Income From Continuing Operation Net Minority Interest,205384000.0,184626000.0,208737000.0,175631000.0,NaN
Reconciled Depreciation,50189000.0,44298000.0,35946000.0,17939000.0,NaN
Reconciled Cost Of Revenue,642430000.0,702054000.0,736448000.0,521374000.0,NaN
EBITDA,326393000.0,306456000.0,356826000.0,251574000.0,NaN
EBIT,276204000.0,262158000.0,320880000.0,233635000.0,NaN
Net Interest Income,-5000.0,103000.0,15000.0,999000.0,NaN
Interest Income,NaN,103000.0,15000.0,999000.0,1503000.0
Normalized Income,205384000.0,196162404.0,243227482.434066,175631000.0,NaN
Net Income From Continuing And Discontinued Operation,205384000.0,184626000.0,208737000.0,175631000.0,NaN
Total Expenses,818633000.0,843885000.0,876072000.0,647196000.0,NaN
Total Operating Income As Reported,276204000.0,246735000.0,275376000.0,233635000.0,NaN
Diluted Average Shares,108809403.0,111880488.0,115762843.0,116252866.0,NaN
Basic Average Shares,108680459.0,111710676.0,115461016.0,115888859.0,NaN
Diluted EPS,1.89,1.65,1.8,1.51,NaN
Basic EPS,1.89,1.65,1.81,1.52,NaN
Diluted NI Availto Com Stockholders,205384000.0,184626000.0,208737000.0,175631000.0,NaN
Net Income Common Stockholders,205384000.0,184626000.0,208737000.0,175631000.0,NaN
Net Income,205384000.0,184626000.0,208737000.0,175631000.0,NaN
Net Income Including Noncontrolling Interests,205384000.0,184626000.0,208737000.0,175631000.0,NaN
Net Income Continuous Operations,205384000.0,184626000.0,208737000.0,175631000.0,NaN
Tax Provision,70815000.0,62212000.0,66654000.0,59003000.0,NaN
Pretax Income,276199000.0,246838000.0,275391000.0,234634000.0,NaN
Other Income Expense,NaN,-15423000.0,-45504000.0,NaN,NaN
Special Income Charges,0.0,-15423000.0,-45504000.0,0.0,NaN
Gain On Sale Of Ppe,0.0,-15423000.0,0.0,0.0,NaN
Other Special Charges,NaN,NaN,-8741000.0,NaN,NaN
Impairment Of Capital Assets,0.0,0.0,54245000.0,0.0,NaN
Net Non Operating Interest Income Expense,-5000.0,103000.0,15000.0,999000.0,NaN
Total Other Finance Cost,5000.0,-103000.0,-15000.0,-999000.0,NaN
Interest Income Non Operating,NaN,103000.0,15000.0,999000.0,1503000.0
Operating Income,276204000.0,262158000.0,320880000.0,233635000.0,NaN
Operating Expense,176203000.0,141831000.0,139624000.0,125822000.0,NaN
Selling General And Administration,176203000.0,141831000.0,139624000.0,125822000.0,NaN
Gross Profit,452407000.0,403989000.0,460504000.0,359457000.0,NaN
Cost Of Revenue,642430000.0,702054000.0,736448000.0,521374000.0,NaN
Total Revenue,1094837000.0,1106043000.0,1196952000.0,880831000.0,NaN
Operating Revenue,1094837000.0,1106043000.0,1196952000.0,880831000.0,NaN

In [17]:
aapl.balance_sheet

,2023-12-31,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Treasury Shares Number,32363306.0,32098410.0,25586601.0,24777502.0,NaN
Ordinary Shares Number,108611537.0,108743423.0,115148152.0,115799503.0,NaN
Share Issued,140974843.0,140841833.0,140734753.0,140577005.0,NaN
Net Debt,3541000.0,209675000.0,NaN,NaN,NaN
Total Debt,32003000.0,253462000.0,35329000.0,35287000.0,NaN
...,...,...,...,...,...
Other Receivables,NaN,NaN,9109000.0,8879000.0,6664000.0
Taxes Receivable,9611000.0,23979000.0,406000.0,7823000.0,NaN
Accounts Receivable,41136000.0,98057000.0,151096000.0,106748000.0,NaN
Cash Cash Equivalents And Short Term Investments,1959000.0,12325000.0,141053000.0,121701000.0,NaN
Cash And Cash Equivalents,1959000.0,12325000.0,141053000.0,121701000.0,NaN

In [18]:
aapl.cashflow

,2023-12-31,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Free Cash Flow,223331000.0,39992000.0,98670000.0,14471000.0,NaN
Repurchase Of Capital Stock,-18450000.0,-398382000.0,-82473000.0,-44854000.0,NaN
Repayment Of Debt,-810000000.0,-203000000.0,-494500000.0,-276000000.0,NaN
Issuance Of Debt,593500000.0,425000000.0,494500000.0,276000000.0,NaN
Capital Expenditure,-166089000.0,-176228000.0,-159394000.0,-172823000.0,NaN
Interest Paid Supplemental Data,51000.0,0.0,0.0,0.0,NaN
Income Tax Paid Supplemental Data,52340000.0,59934000.0,38614000.0,50744000.0,NaN
End Cash Position,1959000.0,12325000.0,141053000.0,121701000.0,NaN
Beginning Cash Position,12325000.0,141053000.0,121701000.0,148833000.0,NaN
Changes In Cash,-10366000.0,-128728000.0,19352000.0,-27132000.0,NaN
Financing Cash Flow,-233697000.0,-176064000.0,-80673000.0,-43768000.0,NaN
Cash Flow From Continuing Financing Activities,-233697000.0,-176064000.0,-80673000.0,-43768000.0,NaN
Net Other Financing Charges,30000.0,-1424000.0,NaN,-360000.0,-518000.0
Proceeds From Stock Option Exercised,1223000.0,1742000.0,1800000.0,1446000.0,NaN
Net Common Stock Issuance,-18450000.0,-398382000.0,-82473000.0,-44854000.0,NaN
Common Stock Payments,-18450000.0,-398382000.0,-82473000.0,-44854000.0,NaN
Net Issuance Payments Of Debt,-216500000.0,222000000.0,0.0,0.0,NaN
Net Short Term Debt Issuance,-216500000.0,222000000.0,0.0,0.0,NaN
Short Term Debt Payments,-810000000.0,-203000000.0,-494500000.0,-276000000.0,NaN
Short Term Debt Issuance,593500000.0,425000000.0,494500000.0,276000000.0,NaN
Investing Cash Flow,-166089000.0,-168884000.0,-158039000.0,-170658000.0,NaN
Cash Flow From Continuing Investing Activities,-166089000.0,-168884000.0,-158039000.0,-170658000.0,NaN
Net Other Investing Changes,NaN,7290000.0,NaN,NaN,NaN
Net Business Purchase And Sale,NaN,NaN,NaN,NaN,0.0
Purchase Of Business,NaN,NaN,NaN,NaN,0.0
Net PPE Purchase And Sale,0.0,54000.0,1355000.0,2165000.0,NaN
Sale Of PPE,0.0,54000.0,1355000.0,2165000.0,NaN
Capital Expenditure Reported,-166089000.0,-176228000.0,-159394000.0,-172823000.0,NaN
Operating Cash Flow,389420000.0,216220000.0,258064000.0,187294000.0,NaN
Cash Flow From Continuing Operating Activities,389420000.0,216220000.0,258064000.0,187294000.0,NaN
Change In Working Capital,116376000.0,-57568000.0,-70309000.0,-26527000.0,NaN
Change In Other Working Capital,14367000.0,-23572000.0,7028000.0,-4759000.0,NaN
Change In Payables And Accrued Expense,11572000.0,-19980000.0,-8758000.0,19008000.0,NaN
Change In Accrued Expense,8875000.0,-14385000.0,-5285000.0,7655000.0,NaN
Change In Payable,2697000.0,-5595000.0,-3473000.0,11353000.0,NaN
Change In Account Payable,2697000.0,-5595000.0,-3473000.0,11353000.0,NaN
Change In Prepaid Assets,-750000.0,7925000.0,-8715000.0,-358000.0,NaN
Change In Inventory,34266000.0,-64454000.0,-15515000.0,-12132000.0,NaN
Change In Receivables,56921000.0,42513000.0,-44349000.0,-28286000.0,NaN
Changes In Account Receivables,56921000.0,42513000.0,-44349000.0,-28286000.0,NaN
Other Non Cash Items,-48000.0,-117000.0,40000.0,51000.0,NaN
Stock Based Compensation,10164000.0,5329000.0,8438000.0,7131000.0,NaN
Asset Impairment Charge,0.0,0.0,54245000.0,0.0,NaN
Deferred Tax,4215000.0,24256000.0,21012000.0,13125000.0,NaN
Deferred Income Tax,4215000.0,24256000.0,21012000.0,13125000.0,NaN
Depreciation Amortization Depletion,50189000.0,44298000.0,35946000.0,17939000.0,NaN
Depreciation And Amortization,50189000.0,44298000.0,35946000.0,17939000.0,NaN
Operating Gains Losses,3140000.0,15396000.0,-45000.0,-56000.0,NaN
Gain Loss On Sale Of PPE,3140000.0,-27000.0,-45000.0,-56000.0,NaN
Net Income From Continuing Operations,205384000.0,184626000.0,208737000.0,175631000.0,NaN

In [2]:
aapl.options

('2024-11-15', '2024-12-20', '2025-01-17', '2025-04-17')

In [3]:
opt = aapl.option_chain('2024-11-15')
# opt.calls
opt.puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,TREX241115P00040000,2024-10-18 15:11:39+00:00,40.0,0.05,0.0,0.0,0.0,0.0,1.0,1,0.500005,False,REGULAR,USD
1,TREX241115P00050000,2024-10-22 13:42:23+00:00,50.0,0.40,0.0,0.0,0.0,0.0,5.0,512,0.250007,False,REGULAR,USD
2,TREX241115P00055000,2024-10-23 13:30:04+00:00,55.0,0.85,0.0,0.0,0.0,0.0,49.0,100,0.125009,False,REGULAR,USD
3,TREX241115P00057500,2024-10-24 19:57:46+00:00,57.5,1.40,0.0,0.0,0.0,0.0,100.0,155,0.125009,False,REGULAR,USD
4,TREX241115P00060000,2024-10-24 19:57:09+00:00,60.0,2.05,0.0,0.0,0.0,0.0,620.0,666,0.062509,False,REGULAR,USD
5,TREX241115P00062500,2024-10-24 15:49:38+00:00,62.5,3.00,0.0,0.0,0.0,0.0,2.0,14,0.031260,False,REGULAR,USD
6,TREX241115P00065000,2024-10-23 14:04:49+00:00,65.0,3.85,0.0,0.0,0.0,0.0,2.0,77,0.000010,True,REGULAR,USD
7,TREX241115P00067500,2024-10-16 17:33:06+00:00,67.5,4.90,0.0,0.0,0.0,0.0,NaN,26,0.000010,True,REGULAR,USD
8,TREX241115P00070000,2024-10-17 19:53:12+00:00,70.0,7.60,0.0,0.0,0.0,0.0,1.0,6,0.000010,True,REGULAR,USD